import assert from 'node:assert/strict';
import {createRoom,addPlayer,startMatch,step,useMove,applyInput,selectFighter,respawn,publicRoom} from '../lib/game/engine';
import {FIGHTERS,ROSTER} from '../lib/game/roster';
const t=1000000;
function setup(){const r=createRoom('ABCDEF','shibuya',t);const a=addPlayer(r,'A',0,'a','secret-a',t);const b=addPlayer(r,'B',1,'b','secret-b',t);const c=addPlayer(r,'C',0,'c','secret-c',t);startMatch(r,t);for(const p of r.players){p.x=0;p.z=0;p.yaw=0;p.spawnProtection=0}b.z=3;c.x=1;return {r,a,b,c}}
let count=0;function test(name:string,f:()=>void){f();count++;console.log('PASS',name)}
test('Full roster: unique IDs, exactly two moves, valid stats',()=>{assert.equal(new Set(ROSTER.map(c=>c.id)).size,81);for(const c of ROSTER){assert.equal(c.moves.length,2);assert(c.hp>0);assert(c.ult.name);if(c.fly)assert(c.moves.some(m=>m.kind==='flight'))}});
test('Guest secrets never enter public snapshots',()=>{const {r}=setup();assert(publicRoom(r).players.every(p=>!('secret'in p)))});
test('Damage, cooldowns, friendly fire and action replay protection',()=>{const {r,a,b,c}=setup();const hp=b.hp,friend=c.hp;applyInput(r,a,{seq:1,actions:['attack']},t+5000);assert(b.hp<hp);const after=b.hp;applyInput(r,a,{seq:1,actions:['attack']},t+6000);assert.equal(b.hp,after);assert.equal(c.hp,friend);useMove(r,a,0,t+5100);assert.equal(b.hp,after)});
test('Movement is bounded by elapsed server time',()=>{const {r,a}=setup();applyInput(r,a,{dx:100000,dz:0,seq:1},t+100000);assert(a.x<=FIGHTERS[a.character].speed*.35+.001)});
test('Everyone unlocked and Tai Lung promoted',()=>{const {r,a}=setup();a.deadUntil=t+1;selectFighter(r,a,'gojo',t+1000);assert.equal(a.character,'gojo');assert.equal(FIGHTERS['tai-lung'].tier,'A');for(const id of ['pain','obito','aoi-todo'])assert.equal(FIGHTERS[id],undefined);startMatch({...r,status:'ended'},t+2000);assert.equal(a.character,'gojo')});
test('King of the Hill control, contest and percentage score',()=>{const {r,a,b,c}=setup();a.x=0;a.z=0;c.x=40;c.z=40;b.x=40;b.z=-40;for(let i=1;i<=9;i++){a.lastSeen=t+i*1000;step(r,t+i*1000)}assert.equal(r.points.length,1);assert.equal(r.points[0].owner,0);assert(r.scores[0]>0&&r.scores[0]<100);b.x=0;b.z=0;b.lastSeen=t+10000;a.lastSeen=t+10000;const score=r.scores[0];step(r,t+10000);assert(r.points[0].contested);assert.equal(r.scores[0],score)});
test('Flight ends after ten seconds',()=>{const {r,a}=setup();a.character='superman';useMove(r,a,1,t+5000);assert.equal(a.flight,t+15000);applyInput(r,a,{seq:1},t+5100);assert.equal(a.y,6);step(r,t+15001);assert.equal(a.y,0);assert.equal(a.flight,0)});
test('Two ultimates per match survive respawn and character swap',()=>{const {r,a}=setup();a.character='superman';a.charge=100;useMove(r,a,3,t+5000);assert.equal(a.ults,1);a.charge=100;useMove(r,a,3,t+20000);assert.equal(a.ults,2);respawn(r,a,t+30000);a.charge=100;useMove(r,a,3,t+40000);assert.equal(a.ults,2)});
test('Jon Jones five-minute lock and one-hit ultimate',()=>{const {r,a,b}=setup();a.character='jon-jones';a.charge=100;useMove(r,a,3,t+299999);assert.equal(a.ults,0);useMove(r,a,3,t+300001);assert.equal(a.ults,1);assert.equal(b.hp,0);a.charge=100;useMove(r,a,3,t+340000);assert.equal(a.ults,1)});
test('Assists credit recent contributors',()=>{const {r,a,b,c}=setup();useMove(r,c,0,t+5000);b.hp=1;useMove(r,a,0,t+6000);assert.equal(a.kills,1);assert.equal(c.assists,1);assert.equal(b.deaths,1)});
test('Headshots depend on vertical beam intersection',()=>{const {r,a,b}=setup();a.character='iron-man';b.z=12;b.hp=300;const ch=FIGHTERS[b.character];a.aimY=Math.atan2(ch.height*.9-FIGHTERS[a.character].height*.72,12);useMove(r,a,2,t+5000);assert.equal(a.headshots,1);assert.equal(a.rangedHits,1);a.aimY=-.8;useMove(r,a,2,t+12000);assert.equal(a.rangedHits,1)});
test('Ten-minute deadline ends match and rematch resets stats',()=>{const {r,a}=setup();a.kills=3;a.assists=2;r.scores=[100,200,40,0];step(r,t+600001);assert.equal(r.status,'ended');assert.equal(r.winner,1);startMatch(r,t+610000);assert.equal(a.kills,0);assert.equal(a.assists,0);assert.equal(a.ults,0)});
console.log(`${count} engine tests passed`);
