"use client";
import {useEffect,useRef,type MutableRefObject} from 'react';
import * as T from 'three';
import {FIGHTERS,TEAM_COLORS} from '@/lib/game/roster';
import {type Room,type Input,type Player} from '@/lib/game/engine';
import {canStand,obstacles} from '@/lib/game/maps';
import {batchMeshes,cameraBoxes,cameraDistance,cameraMovement,disposeObject} from '@/lib/game/rendering';
import {makeFighter,makeCombatFighter,animateFighter} from '@/lib/game/models';
import {buildScenery,label} from '@/lib/game/scenery';
export type Controls={keys:Set<string>;actions:string[];yaw:number;aimY:number;dx:number;dz:number;firing:boolean;touch:boolean;predictedPosition?:{x:number;z:number};sentPositions?:Map<number,{x:number;z:number}>};
export default function Arena({roomRef,playerId,controls,onError}:{roomRef:MutableRefObject<Room|null>;playerId:string;controls:MutableRefObject<Controls>;onError:(s:string)=>void}){
const host=useRef<HTMLDivElement>(null);
useEffect(()=>{const el=host.current,r=roomRef.current;if(!el||!r)return;const coarse=matchMedia('(pointer:coarse)').matches;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:false,powerPreference:'high-performance',stencil:false})}catch{onError('3D graphics are unavailable in this browser. Try a browser with WebGL enabled.');return}renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?.72:1));renderer.shadowMap.enabled=false;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;el.appendChild(renderer.domElement);const scene=new T.Scene();const worldGeometry=buildScenery(scene,r.map);batchMeshes(worldGeometry);const cameraObstacles=cameraBoxes(obstacles(r.map));scene.add(new T.HemisphereLight(r.map==='leaf'?'#fff0d9':'#a6caff','#3b4052',2.5));const sun=new T.DirectionalLight(r.map==='leaf'?'#ffe2b5':'#d9e9ff',3);sun.position.set(-30,65,25);sun.castShadow=false;scene.add(sun);const camera=new T.PerspectiveCamera(58,1,.1,230);
const models=new Map<string,{mesh:T.Group;tag:T.Sprite;ring:T.Mesh;hp:T.Sprite;ch:string;lastX:number;lastZ:number}>();const pointModels=r.points.map(p=>{const mat=new T.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.72,side:T.DoubleSide});const ring=new T.Mesh(new T.RingGeometry(9.45,10,96),mat);ring.rotation.x=-Math.PI/2;ring.position.set(p.x,.06,p.z);scene.add(ring);const beacon=new T.Mesh(new T.CylinderGeometry(.16,.16,12,8),new T.MeshBasicMaterial({color:'#e8f0ff',transparent:true,opacity:.5}));beacon.position.set(p.x,6,p.z);scene.add(beacon);const tag=label('THE HILL');tag.position.set(p.x,13,p.z);tag.scale.set(3.2,.8,1);scene.add(tag);return {ring,beacon,tag}});const effects=new Map<string,{mesh:T.Object3D;at:number}>();
const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(el);let pitch=0;let frame=0,last=performance.now(),lastVersion=-1,lastRender=0;const predicted=new T.Vector3(),visualPosition=new T.Vector3(),desired=new T.Vector3(),headPosition=new T.Vector3(),cameraDelta=new T.Vector3(),target=new T.Vector3(),labelOffset=new T.Vector3();let initialized=false,lastAck=-1;const correction=new T.Vector3();let fpsStart=performance.now(),fpsFrames=0;const perf=document.createElement('output');perf.setAttribute('aria-label','Rendering performance');perf.style.cssText='position:absolute;left:18px;top:100px;color:white;font:12px monospace;background:#101827bb;border-radius:8px;padding:6px 10px;pointer-events:none';el.appendChild(perf);
const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select,[contenteditable=true]'))return;const k=e.key.toLowerCase();controls.current.keys.add(k);if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(!e.repeat){const action=({q:'move1',e:'move2',r:'ult',' ':'attack'} as Record<string,string>)[k];if(action)controls.current.actions.push(action)}};const up=(e:KeyboardEvent)=>controls.current.keys.delete(e.key.toLowerCase());const clear=()=>{controls.current.keys.clear();controls.current.firing=false;controls.current.dx=0;controls.current.dz=0};const move=(e:MouseEvent)=>{if(document.pointerLockElement===renderer.domElement){controls.current.yaw-=e.movementX*.003;pitch=Math.max(-.6,Math.min(.65,pitch-e.movementY*.002));controls.current.aimY=pitch}};const mouseDown=(e:MouseEvent)=>{if(e.button===0){if(document.pointerLockElement!==renderer.domElement)void renderer.domElement.requestPointerLock?.().catch(()=>{});controls.current.firing=true}};const mouseUp=()=>controls.current.firing=false;
window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('mousemove',move);renderer.domElement.addEventListener('mousedown',mouseDown);window.addEventListener('mouseup',mouseUp);
const tick=(time:number)=>{if(document.hidden){last=time;frame=requestAnimationFrame(tick);return}const frameMs=1000/30;if(coarse&&time-lastRender<frameMs-1){frame=requestAnimationFrame(tick);return}if(coarse)lastRender=time-((time-lastRender)%frameMs);const dt=Math.min(.05,(time-last)/1000);last=time;const room=roomRef.current;if(!room){frame=requestAnimationFrame(tick);return}const me=room.players.find(p=>p.id===playerId);const ctl=controls.current;const now=Date.now();if(me){if(!initialized){predicted.set(me.x,me.y,me.z);ctl.yaw=me.yaw;initialized=true}if(room.version!==lastVersion){const sent=ctl.sentPositions?.get(me.lastSeq);if(sent&&me.lastSeq!==lastAck){const ex=me.x-sent.x,ez=me.z-sent.z;if(Math.hypot(ex,ez)>4||me.deadUntil){predicted.set(me.x,me.y,me.z);correction.set(0,0,0)}else{predicted.x+=ex;predicted.z+=ez;correction.x-=ex;correction.z-=ez}lastAck=me.lastSeq;for(const key of ctl.sentPositions!.keys())if(key<=lastAck)ctl.sentPositions!.delete(key)}if(me.deadUntil){predicted.set(me.x,me.y,me.z);correction.set(0,0,0)}lastVersion=room.version;}
let sx=(ctl.keys.has('d')||ctl.keys.has('arrowright')?1:0)-(ctl.keys.has('a')||ctl.keys.has('arrowleft')?1:0),sz=(ctl.keys.has('w')||ctl.keys.has('arrowup')?1:0)-(ctl.keys.has('s')||ctl.keys.has('arrowdown')?1:0);if(!ctl.touch){const direction=cameraMovement(ctl.yaw,sx,sz);ctl.dx=direction.dx;ctl.dz=direction.dz}if(ctl.touch){const enemies=room.players.filter(p=>p.team!==me.team&&!p.deadUntil&&Math.hypot(p.x-me.x,p.z-me.z)<25).sort((a,b)=>Math.hypot(a.x-me.x,a.z-me.z)-Math.hypot(b.x-me.x,b.z-me.z));if(enemies[0]){ctl.yaw=Math.atan2(enemies[0].x-me.x,enemies[0].z-me.z);ctl.aimY=Math.atan2(enemies[0].y+FIGHTERS[enemies[0].character].height*.6-(me.y+FIGHTERS[me.character].height*.72),Math.hypot(enemies[0].x-me.x,enemies[0].z-me.z));}else if(Math.hypot(ctl.dx,ctl.dz)>.1)ctl.yaw=Math.atan2(ctl.dx,ctl.dz)}
const c=FIGHTERS[me.character];if(!me.deadUntil&&me.stun<now){const n=Math.max(1,Math.hypot(ctl.dx,ctl.dz));const nx=predicted.x+ctl.dx/n*c.speed*dt,nz=predicted.z+ctl.dz/n*c.speed*dt;const rr=Math.min(2.4,Math.max(.65,c.height*.36));if(canStand(nx,predicted.z,room.map,rr,me.y>0))predicted.x=nx;if(canStand(predicted.x,nz,room.map,rr,me.y>0))predicted.z=nz}predicted.y=me.y===0?0:T.MathUtils.lerp(predicted.y,me.y,Math.min(1,dt*12));ctl.predictedPosition={x:predicted.x,z:predicted.z};correction.multiplyScalar(Math.exp(-dt*16));visualPosition.copy(predicted).add(correction);const distance=8.5+Math.max(0,c.height-2)*1.8;const camYaw=ctl.touch?Math.PI:ctl.yaw;desired.set(visualPosition.x-Math.sin(camYaw)*distance,visualPosition.y+3.8+Math.max(0,c.height-2),visualPosition.z-Math.cos(camYaw)*distance);headPosition.set(visualPosition.x,visualPosition.y+c.height*.8,visualPosition.z);cameraDelta.copy(desired).sub(headPosition);const cameraLength=cameraDelta.length();cameraDelta.normalize();const safeDistance=cameraDistance(headPosition,cameraDelta,cameraLength,cameraObstacles);if(safeDistance<cameraLength)desired.copy(headPosition).addScaledVector(cameraDelta,safeDistance);camera.position.lerp(desired,1-Math.exp(-dt*12));camera.lookAt(visualPosition.x+Math.sin(camYaw)*25,visualPosition.y+c.height*.72+(ctl.touch?0:Math.tan(pitch)*25),visualPosition.z+Math.cos(camYaw)*25);}
const recentFx=room.fx.filter(f=>now-f.at<300),liveIds=new Set(room.players.map(p=>p.id));for(const p of room.players){const c=FIGHTERS[p.character];let entry=models.get(p.id);if(!entry||entry.ch!==p.character){if(entry){scene.remove(entry.mesh,entry.tag,entry.ring,entry.hp);[entry.mesh,entry.tag,entry.ring,entry.hp].forEach(disposeObject)}const mesh=p.id===playerId?makeFighter(c):makeCombatFighter(c);batchMeshes(mesh);mesh.position.set(p.x,p.y,p.z);scene.add(mesh);const tag=label(p.name,TEAM_COLORS[p.team]);scene.add(tag);const ring=new T.Mesh(new T.RingGeometry(.75,1,16),new T.MeshBasicMaterial({color:TEAM_COLORS[p.team],side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring);const hp=label('━━━━━━━━',TEAM_COLORS[p.team]);hp.scale.set(2,.3,1);scene.add(hp);entry={mesh,tag,ring,hp,ch:p.character,lastX:p.x,lastZ:p.z};models.set(p.id,entry)}const alive=!p.deadUntil;entry.mesh.visible=alive;entry.ring.visible=alive;entry.tag.visible=alive&&p.id!==playerId;entry.hp.visible=alive&&p.id!==playerId;target.set(p.x,p.y,p.z);if(p.id===playerId)entry.mesh.position.copy(predicted).add(correction);else{entry.mesh.position.lerp(target,1-Math.exp(-dt*14));if(p.y===0)entry.mesh.position.y=0;}entry.mesh.rotation.y=p.id===playerId?ctl.yaw:p.yaw;const travelSpeed=Math.hypot(entry.mesh.position.x-entry.lastX,entry.mesh.position.z-entry.lastZ)/Math.max(.001,dt);const moving=Math.min(1,travelSpeed/4);animateFighter(entry.mesh,time*.001,moving,recentFx.some(f=>Math.hypot(f.x-p.x,f.z-p.z)<1),p.y>0,travelSpeed);entry.lastX=entry.mesh.position.x;entry.lastZ=entry.mesh.position.z;labelOffset.set(0,c.height+1,0);entry.tag.position.copy(entry.mesh.position).add(labelOffset);labelOffset.y=c.height+.5;entry.hp.position.copy(entry.mesh.position).add(labelOffset);entry.hp.scale.x=2*Math.max(.05,p.hp/c.hp);entry.ring.position.copy(entry.mesh.position);entry.ring.position.y=.1;entry.ring.scale.setScalar(Math.max(1,c.height*.4));}
for(const [id,e]of models)if(!liveIds.has(id)){scene.remove(e.mesh,e.tag,e.ring,e.hp);[e.mesh,e.tag,e.ring,e.hp].forEach(disposeObject);models.delete(id)}
room.points.forEach((p,i)=>{const col=p.contested?'#ffffff':p.owner<0?'#92a1bd':TEAM_COLORS[p.owner];(pointModels[i].ring.material as T.MeshBasicMaterial).color.set(col);(pointModels[i].beacon.material as T.MeshBasicMaterial).color.set(col);pointModels[i].beacon.scale.y=1+Math.sin(time*.003)*.04;});
for(const fx of room.fx){if(effects.has(fx.id))continue;let mesh:T.Object3D;const material=new T.MeshBasicMaterial({color:fx.color,transparent:true,opacity:.8,side:T.DoubleSide});if(fx.kind==='beam'){const len=Math.hypot(fx.tx-fx.x,fx.tz-fx.z);const b=new T.Mesh(new T.CylinderGeometry(.22,.22,len,8),material);b.position.set((fx.x+fx.tx)/2,1.2,(fx.z+fx.tz)/2);b.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),new T.Vector3(fx.tx-fx.x,0,fx.tz-fx.z).normalize());mesh=b;}else{mesh=new T.Mesh(new T.TorusGeometry(fx.kind==='strike'?2:4,.15,6,48),material);mesh.position.set(fx.x,.4,fx.z);mesh.rotation.x=-Math.PI/2;}scene.add(mesh);effects.set(fx.id,{mesh,at:fx.at})}for(const [id,e]of effects){const age=(now-e.at)/1000;if(age>1.1){scene.remove(e.mesh);if(e.mesh instanceof T.Mesh){e.mesh.geometry.dispose();(e.mesh.material as T.Material).dispose()}effects.delete(id)}else if(e.mesh instanceof T.Mesh){(e.mesh.material as T.MeshBasicMaterial).opacity=Math.max(0,1-age);if(e.mesh.geometry.type!=='CylinderGeometry')e.mesh.scale.setScalar(.6+age*2.5)}}
renderer.render(scene,camera);fpsFrames++;if(time-fpsStart>=1000){const fps=Math.round(fpsFrames*1000/(time-fpsStart));perf.textContent=fps+' FPS';el.dataset.renderCalls=String(renderer.info.render.calls);el.dataset.renderTriangles=String(renderer.info.render.triangles);el.dataset.fps=String(fps);fpsStart=time;fpsFrames=0}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
return()=>{controls.current.predictedPosition=undefined;controls.current.sentPositions?.clear();cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('mousemove',move);window.removeEventListener('mouseup',mouseUp);if(document.pointerLockElement===renderer.domElement)document.exitPointerLock();renderer.dispose();scene.traverse(o=>{if(o instanceof T.Mesh)o.geometry.dispose();if(o instanceof T.Sprite){o.material.map?.dispose();o.material.dispose()}});el.replaceChildren()};},[playerId,roomRef,controls,onError]);
return <div ref={host} className="arena-canvas" aria-label="3D battlefield. Click to aim. WASD to move, mouse to look, Q and E for powers, R for ultimate."/>;
}
