"use client";
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {Fighter,FIGHTER_SCENES,WORLD_SCENES} from '@/lib/game/roster';
import {makeFighter,animateFighter} from '@/lib/game/models';
import {buildBackdrop} from '@/lib/game/scenery';
const PAINTED_WORLDS:Record<string,[string,string]>={
 shibuya:['/arena-atlas.png','0% 0%'],deathstar:['/arena-atlas.png','100% 0%'],leaf:['/arena-atlas.png','0% 100%'],jade:['/arena-atlas.png','100% 100%'],
 manhattan:['/world-atlas-city.jpg','0% 0%'],metropolis:['/world-atlas-city.jpg','0% 0%'],centralcity:['/world-atlas-city.jpg','0% 0%'],city:['/world-atlas-city.jpg','0% 0%'],mansion:['/world-atlas-city.jpg','0% 0%'],gotham:['/world-atlas-city.jpg','100% 0%'],genosha:['/world-atlas-city.jpg','100% 0%'],ring:['/world-atlas-city.jpg','0% 100%'],palace:['/world-atlas-city.jpg','100% 100%'],
 sewer:['/world-atlas-classic.jpg','0% 0%'],dojo:['/world-atlas-classic.jpg','0% 0%'],mushroom:['/world-atlas-classic.jpg','100% 0%'],greenhill:['/world-atlas-classic.jpg','0% 100%'],cybertron:['/world-atlas-classic.jpg','100% 100%'],reactor:['/world-atlas-classic.jpg','100% 100%'],
 wall:['/world-atlas-epic.jpg','0% 0%'],tournament:['/world-atlas-epic.jpg','100% 0%'],ruins:['/world-atlas-epic.jpg','0% 100%'],jungle:['/world-atlas-epic.jpg','100% 100%'],forest:['/world-atlas-epic.jpg','100% 100%'],swamp:['/world-atlas-epic.jpg','100% 100%'],titan:['/world-atlas-epic.jpg','100% 100%'],
 cosmic:['/world-atlas-mythic.jpg','0% 0%'],hell:['/world-atlas-mythic.jpg','100% 0%'],mustafar:['/world-atlas-mythic.jpg','100% 0%'],asgard:['/world-atlas-mythic.jpg','0% 100%'],desert:['/world-atlas-mythic.jpg','100% 100%']
};
export default function CharacterPreview({fighter,fullStage=false,alignRight=false}:{fighter:Fighter;fullStage?:boolean;alignRight?:boolean}){const host=useRef<HTMLDivElement>(null);const [closeup,setCloseup]=useState(!fullStage);useEffect(()=>{const el=host.current;if(!el)return;const coarse=matchMedia('(pointer:coarse)').matches;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:!coarse,alpha:true,powerPreference:'high-performance'})}catch{return}renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1:1.25));renderer.shadowMap.enabled=!coarse;renderer.shadowMap.type=T.BasicShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;el.appendChild(renderer.domElement);const scene=new T.Scene();const camera=new T.PerspectiveCamera(34,1,.1,150);scene.add(new T.HemisphereLight('#eaf3ff','#485064',3));const key=new T.DirectionalLight('#fff1da',4);key.position.set(4,9,7);key.castShadow=!coarse;key.shadow.mapSize.set(1024,1024);scene.add(key);const rim=new T.DirectionalLight(fighter.accent,3);rim.position.set(-4,4,-3);scene.add(rim);const theme=(FIGHTER_SCENES[fighter.id]||WORLD_SCENES[fighter.world])?.scene||'city';const painted=PAINTED_WORLDS[theme]||PAINTED_WORLDS.city;if(painted){scene.background=null;el.style.backgroundImage=`linear-gradient(0deg,#21122e99,transparent 75%),url('${painted[0]}')`;el.style.backgroundSize='100% 100%,200% 200%';el.style.backgroundPosition='center,'+painted[1];}else{el.style.backgroundImage='none';buildBackdrop(scene,theme);}const model=makeFighter(fighter);scene.add(model);const h=fighter.height;camera.position.set(h*(closeup?.20:.65),h*(closeup?.87:.82),h*(closeup?1.3:fullStage?2.9:2.5));camera.lookAt(0,h*(closeup?.67:.54),0);const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.setViewOffset(el.clientWidth,el.clientHeight,fullStage&&el.clientWidth>800?el.clientWidth*(alignRight?-.19:.23):0,0,el.clientWidth,el.clientHeight);camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(el);let frame=0,visible=true;const io=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting});io.observe(el);const tick=(t:number)=>{if(visible&&!document.hidden){model.rotation.y=Math.sin(t*.0002)*.24-.14;animateFighter(model,t*.001,0);renderer.render(scene,camera)}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();renderer.dispose();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}});el.replaceChildren()};},[fighter,closeup,fullStage,alignRight]);return <><div ref={host} className="character-render" aria-label={`3D preview of ${fighter.name}`}/><button className="preview-framing" onClick={()=>setCloseup(!closeup)} aria-pressed={closeup}>{closeup?'Full fighter ↗':'Face detail ↗'}</button></>}
