import {FIGHTERS,ROSTER,TIERS,COSTS,TEAMS,fighterPrimary,fighterPower,fighterUltimate,type Fighter,type Move} from './roster';
import {POINTS,SPAWNS,canStand,lineClear} from './maps';
export type Player={id:string;secret?:string;name:string;team:number;character:string;x:number;z:number;y:number;yaw:number;hp:number;bp:number;charge:number;ults:number;kills:number;deaths:number;assists:number;headshots:number;rangedHits:number;aimY:number;attackers:Record<string,{damage:number;at:number}>;damage:number;captures:number;cooldowns:number[];shield:number;stun:number;flight:number;deadUntil:number;lastSeen:number;lastInput:number;lastSeq:number;bot:boolean;form:number;spawnProtection:number};
export type Point={id:string;x:number;z:number;owner:number;capturing:number;progress:number;contested:boolean};
export type Fx={id:string;x:number;z:number;tx:number;tz:number;kind:string;color:string;at:number;character?:string;move?:string;ultimate?:boolean};
export type Room={code:string;host:string;map:string;status:'lobby'|'playing'|'ended';players:Player[];points:Point[];scores:number[];started:number;updated:number;created:number;winner:number;feed:{id:string;text:string;at:number}[];fx:Fx[];version:number};
export type Input={dx?:number;dz?:number;yaw?:number;aimY?:number;actions?:string[];seq?:number};
export const MAX_SCORE=100;export const MATCH_LENGTH=600000;export const HILL_RADIUS=10;export const HILL_SCORE_RATE=.5;
export function fighter(p:Player){return FIGHTERS[p.character]||ROSTER[0]}
export function createRoom(code:string,map:string,now:number):Room{return {code,host:'',map,status:'lobby',players:[],points:POINTS.map(p=>({...p,owner:-1,capturing:-1,progress:0,contested:false})),scores:[0,0,0,0],started:0,updated:now,created:now,winner:-1,feed:[],fx:[],version:0}}
export function addPlayer(r:Room,name:string,team:number,id:string,secret:string,now:number,bot=false){if(r.players.length>=24)throw Error('Room is full (24 players).');if(r.players.filter(p=>p.team===team).length>=6)throw Error('That team is full. Choose another.');const s=SPAWNS[team];const ch=bot?ROSTER[(r.players.length*7)%ROSTER.length]:FIGHTERS['gojo'];const p:Player={id,secret,name,team,character:ch.id,x:s.x,z:s.z,y:0,yaw:Math.atan2(-s.x,-s.z),hp:ch.hp,bp:0,charge:0,ults:0,kills:0,deaths:0,assists:0,headshots:0,rangedHits:0,aimY:0,attackers:{},damage:0,captures:0,cooldowns:[0,0,0,0],shield:0,stun:0,flight:0,deadUntil:0,lastSeen:now,lastInput:now,lastSeq:0,bot,form:0,spawnProtection:now+4000};r.players.push(p);if(!r.host&&!bot)r.host=id;return p;}
export function announce(r:Room,text:string,now:number){r.feed.unshift({id:crypto.randomUUID(),text,at:now});r.feed=r.feed.slice(0,8)}
export function selectFighter(r:Room,p:Player,id:string,now:number){const c=FIGHTERS[id];if(!c)throw Error('Unknown fighter.');if(r.status==='ended')throw Error('Start a rematch first.');if(r.status==='playing'&&!p.deadUntil)throw Error('Change fighters after you are eliminated.');p.character=id;p.hp=c.hp;p.flight=0;p.form=0;p.cooldowns=[0,0,0,0];if(r.status==='playing'&&now>=p.deadUntil)respawn(r,p,now);}
export function respawn(r:Room,p:Player,now:number){const s=SPAWNS[p.team];p.x=s.x;p.z=s.z;for(let attempt=0;attempt<16;attempt++){const x=s.x+(Math.random()-.5)*3,z=s.z+(Math.random()-.5)*3;if(canStand(x,z,r.map,radius(p))){p.x=x;p.z=z;break}}p.y=0;p.hp=fighter(p).hp;p.deadUntil=0;p.shield=0;p.stun=0;p.flight=0;p.spawnProtection=now+4000;p.lastInput=now;p.attackers={};}
export function startMatch(r:Room,now:number){if(r.status==='playing')throw Error('The match has already started.');r.status='playing';r.started=now;r.updated=now;r.scores=[0,0,0,0];r.winner=-1;r.fx=[];r.feed=[];r.points=POINTS.map(p=>({...p,owner:-1,capturing:-1,progress:0,contested:false}));for(const p of r.players){p.bp=0;p.charge=0;p.ults=0;p.kills=0;p.deaths=0;p.damage=0;p.captures=0;p.assists=0;p.headshots=0;p.rangedHits=0;p.attackers={};p.cooldowns=[0,0,0,0];respawn(r,p,now)}announce(r,'KING OF THE HILL — control the center to reach 100%.',now);}
function radius(p:Player){return Math.min(2.4,Math.max(.65,fighter(p).height*.36))}
function movePlayer(r:Room,p:Player,dx:number,dz:number,dt:number,now:number){if(p.deadUntil||p.stun>now)return;const n=Math.hypot(dx,dz);if(n>1){dx/=n;dz/=n}let speed=fighter(p).speed;if(p.character==='furious-five'&&p.form===1)speed*=1.3;const s=speed*dt;const flying=p.flight>now;const nx=p.x+dx*s,nz=p.z+dz*s;if(canStand(nx,p.z,r.map,radius(p),flying))p.x=nx;if(canStand(p.x,nz,r.map,radius(p),flying))p.z=nz;p.y=flying?6:0;}
function hurt(r:Room,a:Player,b:Player,amount:number,now:number,headshot=false,ranged=false){if(a.team===b.team||b.deadUntil||b.spawnProtection>now)return;const damage=Math.min(b.hp,amount*(b.shield>now?.2:1));b.hp-=damage;if(ranged&&damage>0){a.rangedHits=(a.rangedHits||0)+1;if(headshot)a.headshots=(a.headshots||0)+1}b.attackers||={};b.attackers[a.id]={damage:(b.attackers[a.id]?.damage||0)+damage,at:now};a.damage+=damage;a.bp+=damage*.65;a.charge=Math.min(100,a.charge+damage*.11);if(b.hp<=0){b.hp=0;b.deadUntil=now+7000;b.flight=0;b.deaths++;a.kills++;a.bp+=90;for(const [id,hit] of Object.entries(b.attackers)){if(id!==a.id&&now-hit.at<10000&&hit.damage>=10){const helper=r.players.find(p=>p.id===id);if(helper){helper.assists=(helper.assists||0)+1;helper.bp+=45}}}b.attackers={};announce(r,`${a.name} eliminated ${b.name}`,now);}}
function effect(r:Room,p:Player,kind:string,now:number,range:number,move='',ultimate=false){r.fx.push({id:crypto.randomUUID(),x:p.x,z:p.z,tx:p.x+Math.sin(p.yaw)*range,tz:p.z+Math.cos(p.yaw)*range,kind,color:fighter(p).accent,at:now,character:p.character,move,ultimate})}
export function useMove(r:Room,p:Player,slot:number,now:number){if(p.deadUntil||p.stun>now||p.cooldowns[slot]>now)return;const c=fighter(p);const ult=slot===3;const m:Move=slot===0||slot===2?fighterPrimary(c):ult?fighterUltimate(c):fighterPower(c);if(ult){if(p.charge<100||p.ults>=(c.id==='jon-jones'?1:2)||(c.id==='jon-jones'&&now-r.started<300000))return;p.charge=0;p.ults++;}p.spawnProtection=0;p.cooldowns[slot]=now+(slot===0?Math.min(.9,m.cooldown):m.cooldown)*1000;const amp=1+Math.min(4,Math.floor((now-r.started)/120000))*.1;const dmg=c.damage*(ult?4.3:slot===0?1:1.9)*amp;let range=m.kind==='beam'?ult?38:25:m.kind==='strike'?c.range+Math.max(0,c.height-2)*.35:ult?16:9;
if(m.kind==='flight'){p.flight=now+10000;effect(r,p,'flight',now,0,m.name,ult);return}if(m.kind==='shield'){p.shield=now+(ult?9000:4000);effect(r,p,'shield',now,0,m.name,ult);return}if(m.kind==='heal'){p.hp=Math.min(c.hp,p.hp+c.hp*(ult?.8:.28));effect(r,p,'heal',now,0,m.name,ult);return}if(m.kind==='switch'){p.form=(p.form+1)%5;effect(r,p,'switch',now,0,m.name,ult);return}if(m.kind==='dash'){for(let i=0;i<12;i++)movePlayer(r,p,Math.sin(p.yaw),Math.cos(p.yaw),.1,now);range=5}effect(r,p,m.kind,now,range,m.name,ult);
for(const b of r.players){if(b.team===p.team||b.deadUntil||Math.abs(b.y-p.y)>8)continue;const d=Math.hypot(b.x-p.x,b.z-p.z);if(d>range+radius(b))continue;const projection=(b.x-p.x)*Math.sin(p.yaw)+(b.z-p.z)*Math.cos(p.yaw);const side=Math.abs((b.x-p.x)*Math.cos(p.yaw)-(b.z-p.z)*Math.sin(p.yaw));if(m.kind==='beam'&&(projection<0||side>(ult?3.5:1.6)+radius(b)))continue;if((m.kind==='strike'||m.kind==='stun')&&projection<-.5)continue;if(!lineClear(p.x,p.z,b.x,b.z,r.map,p.y>0&&b.y>0))continue;const hitY=p.y+c.height*.72+Math.tan(p.aimY||0)*d;const ranged=m.kind==='beam';if(ranged&&(hitY<b.y||hitY>b.y+fighter(b).height*1.08))continue;const headshot=ranged&&hitY>=b.y+fighter(b).height*.82;hurt(r,p,b,ult&&c.id==='jon-jones'?100000:dmg*(p.character==='furious-five'&&p.form===0?1.2:1)*(headshot?1.5:1),now,headshot,ranged);if(m.kind==='stun')b.stun=now+(ult?2400:1000);if(m.kind==='pull'&&!b.deadUntil){const nx=p.x+(b.x-p.x)*.3,nz=p.z+(b.z-p.z)*.3;if(canStand(nx,nz,r.map,radius(b),b.y>0)){b.x=nx;b.z=nz}}}
}
export function applyInput(r:Room,p:Player,input:Input,now:number){p.lastSeen=now;if(r.status!=='playing')return;const dt=Math.min(.35,Math.max(0,(now-p.lastInput)/1000));p.lastInput=now;if(p.deadUntil)return;if(Number.isFinite(input.aimY))p.aimY=Math.max(-.8,Math.min(.8,Number(input.aimY)));if(Number.isFinite(input.yaw))p.yaw=Number(input.yaw)%(Math.PI*2);movePlayer(r,p,Math.max(-1,Math.min(1,Number(input.dx)||0)),Math.max(-1,Math.min(1,Number(input.dz)||0)),dt,now);if(Number.isInteger(input.seq)&&input.seq!>p.lastSeq){p.lastSeq=input.seq!;for(const action of (input.actions||[]).slice(0,4)){const slot=action==='attack'?0:action==='power'?1:action==='ult'?3:-1;if(slot>=0)useMove(r,p,slot,now)}}}
export function step(r:Room,now:number){const dt=Math.min(1,Math.max(0,(now-r.updated)/1000));r.updated=now;r.fx=r.fx.filter(f=>now-f.at<1200);if(r.status!=='playing')return;
for(const p of r.players){if(p.flight&&p.flight<=now){p.flight=0;p.y=0;if(!canStand(p.x,p.z,r.map,radius(p))) {for(let d=1;d<12;d++){let found=false;for(let a=0;a<8;a++){const x=p.x+Math.sin(a*Math.PI/4)*d,z=p.z+Math.cos(a*Math.PI/4)*d;if(canStand(x,z,r.map,radius(p))){p.x=x;p.z=z;found=true;break}}if(found)break}}}if(!p.deadUntil){p.charge=Math.min(100,p.charge+dt*.7);if(p.bot){const target=r.points.filter(o=>o.owner!==p.team)[Math.abs(r.players.indexOf(p))%Math.max(1,r.points.filter(o=>o.owner!==p.team).length)]||r.points[r.players.indexOf(p)%r.points.length];const enemy=r.players.filter(e=>e.team!==p.team&&!e.deadUntil&&e.lastSeen>now-15000).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];const near=enemy&&Math.hypot(enemy.x-p.x,enemy.z-p.z)<18;const tx=near?enemy.x:target.x,tz=near?enemy.z:target.z;const angle=Math.atan2(tx-p.x,tz-p.z);p.yaw=angle;if(near)p.aimY=Math.atan2(enemy.y+fighter(enemy).height*.6-(p.y+fighter(p).height*.72),Math.hypot(enemy.x-p.x,enemy.z-p.z));const ox=p.x,oz=p.z;if(Math.hypot(tx-p.x,tz-p.z)>3)movePlayer(r,p,Math.sin(angle),Math.cos(angle),dt*.8,now);if(Math.hypot(p.x-ox,p.z-oz)<.02){movePlayer(r,p,Math.sin(angle+1.3),Math.cos(angle+1.3),dt,now)}if(near){useMove(r,p,0,now);useMove(r,p,1,now);useMove(r,p,2,now);useMove(r,p,3,now)}}}else if(p.bot&&p.deadUntil<=now){p.character=ROSTER[Math.floor(Math.random()*ROSTER.length)].id;respawn(r,p,now)}if(p.bot)p.lastSeen=now;}
for(const o of r.points){const occupants=r.players.filter(p=>!p.deadUntil&&p.y===0&&p.lastSeen>now-10000&&Math.hypot(p.x-o.x,p.z-o.z)<HILL_RADIUS);const teams=[...new Set(occupants.map(p=>p.team))];o.contested=teams.length>1;if(teams.length===1){const team=teams[0];if(o.owner!==team){o.owner=team;o.capturing=team;for(const p of occupants.filter(p=>p.team===team)){p.bp+=35;p.captures++}announce(r,`${TEAMS[team]} controls the hill`,now)}r.scores[team]=Math.min(MAX_SCORE,r.scores[team]+dt*HILL_SCORE_RATE);o.progress=r.scores[team];for(const p of occupants){p.bp+=dt*7;p.charge=Math.min(100,p.charge+dt)}}else if(!teams.length){o.owner=-1;o.capturing=-1;o.progress=0}else{o.capturing=-1}}
if(now-r.started>=MATCH_LENGTH||Math.max(...r.scores)>=MAX_SCORE){r.status='ended';const max=Math.max(...r.scores);r.winner=r.scores.filter(s=>Math.abs(s-max)<.01).length===1?r.scores.indexOf(max):-1;announce(r,r.winner<0?'Draw — run it back.':`${TEAMS[r.winner]} team wins!`,now)}
}
export function publicRoom(r:Room){return {...r,players:r.players.map(({secret,...p})=>p)}}
