import {gameDb} from '@/lib/game/database';
import {createRoom,addPlayer,startMatch,selectFighter,respawn,step,applyInput,publicRoom,type Room} from '@/lib/game/engine';
import {FIGHTERS} from '@/lib/game/roster';
import {MAPS} from '@/lib/game/maps';
export const dynamic='force-dynamic';
function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
export async function POST(req:Request){try{if(req.headers.get('origin')&&new URL(req.headers.get('origin')!).host!==new URL(req.url).host)return reply({error:'Invalid origin.'},403);const raw=await req.text();if(raw.length>4096)return reply({error:'Request too large.'},413);const b=JSON.parse(raw);const now=Date.now();const db=gameDb();if(['create','join'].includes(b.op)&&b.character!==undefined&&!Object.hasOwn(FIGHTERS,String(b.character)))throw Error('Choose a valid character.');
if(b.op==='create'){const name=String(b.name||'').trim().slice(0,18);if(!name)throw Error('Enter your callsign.');if(!MAPS.some(m=>m.id===b.map))throw Error('Choose a battlefield.');const team=Number(b.team)||0;if(!Number.isInteger(team)||team<0||team>3)throw Error('Choose a team.');const code=crypto.randomUUID().replace(/-/g,'').slice(0,6).toUpperCase();const r=createRoom(code,b.map,now);const token=crypto.randomUUID();const id=crypto.randomUUID();const player=addPlayer(r,name,team,id,token,now);if(b.character){player.character=b.character;player.hp=FIGHTERS[b.character].hp;}await db.prepare('INSERT INTO game_rooms (code,state,version,updated) VALUES (?,?,?,?)').bind(code,JSON.stringify(r),0,now).run();return reply({room:publicRoom(r),id,token});}
const code=String(b.code||'').toUpperCase();if(!/^[A-F0-9]{6}$/.test(code))throw Error('Enter a valid six-character room code.');
for(let attempt=0;attempt<7;attempt++){const row=await db.prepare('SELECT state,version FROM game_rooms WHERE code=?').bind(code).first<{state:string;version:number}>();if(!row)return reply({error:'Room not found. Check the code or create a room.'},404);const r:Room=JSON.parse(row.state);for(const p of r.players){if(!FIGHTERS[p.character]){p.character="gojo";p.hp=FIGHTERS.gojo.hp;}if(p.bot)p.name=FIGHTERS[p.character].name;}if(now-r.updated>86400000)return reply({error:'This room expired. Create a fresh room.'},410);let player=r.players.find(p=>p.id===b.id&&p.secret===b.token&&!p.bot);let token:string|undefined,id:string|undefined;if(b.op==='join'){const name=String(b.name||'').trim().slice(0,18);if(!name)throw Error('Enter your callsign.');const team=Number(b.team);if(!Number.isInteger(team)||team<0||team>3)throw Error('Choose a team.');if(r.status==='ended')throw Error('This match has ended. Ask the host to start a rematch.');const botIndex=r.players.findIndex(p=>p.bot&&p.team===team);if(botIndex>=0)r.players.splice(botIndex,1);token=crypto.randomUUID();id=crypto.randomUUID();player=addPlayer(r,name,team,id,token,now);if(b.character){player.character=b.character;player.hp=FIGHTERS[b.character].hp;}}else{if(!player)return reply({error:'Session expired. Rejoin the room.'},401);player.lastSeen=now;}
step(r,now);
if(b.op==='start'){if(r.host!==player.id)throw Error('Only the host can start the match.');startMatch(r,now)}else if(b.op==='bots'){if(r.host!==player.id||r.status!=='lobby')throw Error('Only the host can add training bots in the lobby.');for(let t=0;t<4;t++)while(r.players.filter(p=>p.team===t).length<3){const n=r.players.filter(p=>p.team===t).length;addPlayer(r,`BOT ${['EMBER','VOLT','JADE','SOL'][t]} ${n+1}`,t,crypto.randomUUID(),'',now,true)}}else if(b.op==='select')selectFighter(r,player,String(b.character),now);else if(b.op==='respawn'){if(r.status!=='playing'||!player.deadUntil||now<player.deadUntil)throw Error('Respawn is not ready yet.');respawn(r,player,now)}else if(b.op==='input')applyInput(r,player,b.input||{},now);else if(b.op==='leave'){r.players=r.players.filter(p=>p.id!==player!.id);if(r.host===player.id)r.host=r.players.find(p=>!p.bot)?.id||''}else if(!['join','poll'].includes(b.op))throw Error('Unknown action.');
r.version=row.version+1;const result=await db.prepare('UPDATE game_rooms SET state=?,version=?,updated=? WHERE code=? AND version=?').bind(JSON.stringify(r),r.version,now,code,row.version).run();if(result.meta.changes===1)return reply({room:publicRoom(r),...(token?{token,id}:{})});}
return reply({error:'Battlefield is busy. Reconnecting…'},409);
}catch(e){const message=e instanceof Error?e.message:'Unable to connect.';if(/D1|SQLITE|binding/i.test(message)){console.error('Game storage error',message);return reply({error:'The battlefield is temporarily unavailable. Please retry.'},503)}return reply({error:message},400)}}
